# Generated by Django 2.2 on 2019-11-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_token_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Ссылки на другие информыции о вас '),
        ),
    ]
