# Generated by Django 2.2 on 2019-11-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(5, 'Суппер'), (4, 'Хороший'), (3, 'нормально'), (2, 'ну как то не тока с продуктом'), (1, 'атвратительный')], verbose_name='Категория'),
        ),
    ]
